### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by Nekmo** [jcstroud/pyfscache#7]
```
(anime-news-network) [nekmo@shiori ~/Workspace/anime-news-network] (master)$ pip install pyfscache
Collecting pyfscache
  Downloading pyfscache-0.9.12.tar.gz (79kB)
    100% |████████████████████████████████| 81kB 486kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-82g9tu4t/pyfscache/setup.py", line 5, in <module>
        from StringIO import StringIO
    ImportError: No module named 'StringIO'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-82g9tu4t/pyfscache/
(anime-news-network) [nekmo@shiori ~/Workspace/anime-news-network] (master)$ 
```

**Comment by ghost** [comment]
Any updates on this?
